networks:
  default:
    driver: bridge

services:
  influxdb:
    image: influxdb:1.8
    container_name: kgb-influxdb
    networks:
      - default
    ports:
      - "8086:8086"
    volumes:
      - g:\tools\influxdb\data2:/var/lib/influxdb
    env_file:
      - src/main/docker/kgb.env
  katya-gluco-bot:
    networks:
      - default
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.jvm
    env_file:
      - src/main/docker/kgb.env
    depends_on:
      - influxdb
#  zookeeper:
#    image: bitnami/zookeeper:latest
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#
#  telegraf:
#    image: telegraf:latest
#    container_name: telegraf
#    depends_on:
#      - influxdb
#      - kafka
#    volumes:
#      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    network_mode: "host" # или используйте общую сеть, если не на Linux
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "8080:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092
#    depends_on:
#      - kafka

volumes:
  influxdb-data:
