version: '3.8'

services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /home/sergei/tools/influxdb/data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=xdrip
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
  katya-gluco-bot:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    environment:
      - INFLUXDB_SERVER_URL_1=${INFLUXDB_SERVER_URL_1}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_DB=${INFLUXDB_DB}
      - TELEGRAM_BOT_API_URL=${TELEGRAM_BOT_API_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID_1=${TELEGRAM_CHAT_ID_1}
      - TELEGRAM_CHAT_ID_2=${TELEGRAM_CHAT_ID_2}

#  zookeeper:
#    image: bitnami/zookeeper:latest
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#
#  telegraf:
#    image: telegraf:latest
#    container_name: telegraf
#    depends_on:
#      - influxdb
#      - kafka
#    volumes:
#      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    network_mode: "host" # или используйте общую сеть, если не на Linux
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "8080:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092
#    depends_on:
#      - kafka

volumes:
  influxdb-data:
