CREATE SEQUENCE IF NOT EXISTS JG_POLLS_ID_SEQ;

CREATE TABLE IF NOT EXISTS JG_POLLS
(
    ID            INT8         NOT NULL,
    TIME_LOCAL     TIMESTAMP NOT NULL,
    MIN_SINCE_START     INT4 NOT NULL,
    GLUCOSE     INT4 NOT NULL,
    TREND  VARCHAR(15),
    RATE_OF_CHANGE NUMERIC NOT NULL,
    CONSTRAINT JG_P_PKEY PRIMARY KEY (ID)
);