CREATE SEQUENCE IF NOT EXISTS NS_ENTRY_ID_SEQ;

CREATE TABLE IF NOT EXISTS NS_ENTRY
(
    ID            INT8         NOT NULL,
    TYP VARCHAR(10) NOT NULL,
    DEVICE VARCHAR(50) NOT NULL,
    SGV_TIME     TIMESTAMP NOT NULL,
    EPOCH_TIME INT8 NOT NULL,
    SGV     INT4 NOT NULL,
    DELTA NUMERIC,
    DIRECTION     VARCHAR(20),
    NOISE  INT4,
    FILTERED INT4,
    UNFILTERED INT4,
    RSSI INT4,
    CONSTRAINT NSE_P_PKEY PRIMARY KEY (ID)
);